##
## EPITECH PROJECT, 2025
## Makefile
## File description:
## Makefile
##

all:
	make -C ./my
	make -C ./lib_vectors

debug:
	make debug -C ./my
	make debug -C ./lib_vectors

clean:
	make clean -C ./my
	make clean -C ./lib_vectors

fclean:
	make fclean -C ./my
	make fclean -C ./lib_vectors

re:	fclean all

.PHONY: all debug clean fclean
